<?php require (is_file(__DIR__.'/../../app/bootstrap.php') ? __DIR__.'/../../app/bootstrap.php' : '/var/www/appsbilling-commercial-platform/app/bootstrap.php'); csrf_check(); $u=require_tenant_user(); $tenant=q1('SELECT * FROM tenants WHERE id=?',[(int)$u['tenant_id']]); $db=tenant_db_path($tenant); $pdo=new PDO('sqlite:'.$db); $pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION); $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE,PDO::FETCH_ASSOC);
if($_SERVER['REQUEST_METHOD']==='POST'){
    try{
        $brand=trim($_POST['office_brand'] ?? $tenant['company_name']);
        if($brand==='') $brand=$tenant['company_name'];
        tenant_set_setting($pdo,'office_brand',$brand);
        if($fn=process_logo_upload('app_logo',$tenant,'app-logo',900,524288)) tenant_set_setting($pdo,'app_logo',tenant_public_upload_url($tenant,$fn));
        if($fn=process_logo_upload('receipt_logo',$tenant,'receipt-logo',1200,524288)) tenant_set_setting($pdo,'receipt_logo',tenant_public_upload_url($tenant,$fn));
        tenant_set_setting($pdo,'copyright','PT Denta Sejahtera Group dan Ananta Satriya Ferdian');
        log_event((int)$tenant['id'],'tenant_user',(int)$u['id'],'tenant_branding_updated','Branding/logo tenant diperbarui.');
        flash('ok','Pengaturan branding tersimpan. Logo otomatis divalidasi dan dikompres bila server mendukung.');
    }catch(Throwable $e){ flash('err',$e->getMessage()); }
    redirect(app_url('tenant/settings.php'));
}
$appLogo=tenant_setting($pdo,'app_logo'); $receiptLogo=tenant_setting($pdo,'receipt_logo'); $brand=tenant_setting($pdo,'office_brand',$tenant['company_name']); $copyright=tenant_setting($pdo,'copyright','PT Denta Sejahtera Group dan Ananta Satriya Ferdian');
render_header('Pengaturan Branding Mitra'); ?>
<div class="dash"><aside class="side"><div class="brand"><span class="brand-mark">AB</span><span><?=e($tenant['company_name'])?></span></div><a href="<?=app_url('tenant/dashboard.php')?>">Dashboard</a><a class="active" href="<?=app_url('tenant/settings.php')?>">Logo & Branding</a><a href="<?=app_url('tenant/logout.php')?>">Keluar</a><p class="footer-note">No Akun: <?=e($tenant['account_no'] ?? '-')?></p></aside><main class="main"><div class="topline"><div><h1>Logo & Branding</h1><p>Atur logo aplikasi dan logo kwitansi untuk <?=e($tenant['company_name'])?>.</p></div><span class="badge active">branding</span></div><?php if($m=flash('ok')):?><div class="alert alert-ok"><?=e($m)?></div><?php endif;?><?php if($m=flash('err')):?><div class="alert alert-danger"><?=e($m)?></div><?php endif;?>
<div class="grid detail-grid"><section class="card"><h3>Upload Logo</h3><form class="form" method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><div class="field"><label>Nama brand di kwitansi</label><input class="input" name="office_brand" value="<?=e($brand)?>"></div><div class="field"><label>Logo aplikasi JPG/PNG</label><input class="input" type="file" name="app_logo" accept="image/png,image/jpeg"><small>Disarankan kotak/rapi. Maksimal 5MB sebelum kompres, target hasil ±512KB.</small></div><div class="field"><label>Logo kwitansi JPG/PNG</label><input class="input" type="file" name="receipt_logo" accept="image/png,image/jpeg"><small>Disarankan horizontal transparan/putih. Jika terlalu besar akan dicoba kompres.</small></div><button class="btn btn-primary">Simpan Branding</button></form></section><section class="card"><h3>Preview</h3><div class="logo-preview"><div><small>Logo aplikasi</small><?php if($appLogo):?><img src="<?=e($appLogo)?>" alt="Logo aplikasi"><?php else:?><div class="empty-logo">Belum ada</div><?php endif;?></div><div><small>Logo kwitansi</small><?php if($receiptLogo):?><img src="<?=e($receiptLogo)?>" alt="Logo kwitansi"><?php else:?><div class="empty-logo">Belum ada</div><?php endif;?></div></div><p><b>Copyright:</b><br><?=e($copyright)?></p><p class="footer-note">Copyright dikunci sesuai arahan pusat.</p></section></div></main></div><?php render_footer(); ?>
