<?php require (is_file(__DIR__.'/../../app/bootstrap.php') ? __DIR__.'/../../app/bootstrap.php' : '/var/www/appsbilling-commercial-platform/app/bootstrap.php'); csrf_check(); $admin=require_superadmin();
if($_SERVER['REQUEST_METHOD']==='POST'){
 $action=$_POST['action']??''; $id=(int)($_POST['tenant_id']??0); $t=q1('SELECT * FROM tenants WHERE id=?',[$id]); if(!$t){ flash('err','Tenant tidak ditemukan.'); redirect(app_url('superadmin/index.php')); }
 if($action==='approve'){
   execsql('UPDATE tenants SET status=?,approved_at=?,disabled_at=NULL,deleted_at=NULL WHERE id=?',['active',now(),$id]); tenant_db_path($t); log_event($id,'superadmin',(int)$admin['id'],'tenant_approved','Tenant disetujui dan DB dipastikan tersedia.'); flash('ok','Tenant disetujui dan DB dibuat/aktif.');
 } elseif($action==='disable'){
   execsql('UPDATE tenants SET status=?,disabled_at=? WHERE id=?',['disabled',now(),$id]); log_event($id,'superadmin',(int)$admin['id'],'tenant_disabled','Tenant dinonaktifkan sementara.'); flash('ok','Tenant dinonaktifkan.');
 } elseif($action==='reactivate'){
   execsql('UPDATE tenants SET status=?,disabled_at=NULL,deleted_at=NULL WHERE id=?',['active',$id]); tenant_db_path($t); log_event($id,'superadmin',(int)$admin['id'],'tenant_reactivated','Tenant diaktifkan kembali.'); flash('ok','Tenant aktif kembali.');
 } elseif($action==='delete'){
   execsql('UPDATE tenants SET status=?,deleted_at=? WHERE id=?',['deleted',now(),$id]); log_event($id,'superadmin',(int)$admin['id'],'tenant_deleted_soft','Tenant soft-deleted; DB tidak dihapus otomatis.'); flash('ok','Tenant ditandai deleted. DB tidak dihapus otomatis.');
 }
 redirect(app_url('superadmin/index.php'));
}
$tenants=qall('SELECT t.*,td.db_path,(SELECT COUNT(*) FROM tenant_users tu WHERE tu.tenant_id=t.id) user_count FROM tenants t LEFT JOIN tenant_databases td ON td.tenant_id=t.id ORDER BY t.id DESC');
$counts=['pending'=>0,'active'=>0,'disabled'=>0,'deleted'=>0]; foreach($tenants as $t){$counts[$t['status']]=$counts[$t['status']]??0; $counts[$t['status']]++;}
render_header('Superadmin Dashboard'); ?><div class="dash"><aside class="side"><div class="brand"><span class="brand-mark">AB</span><span>Superadmin</span></div><a class="active" href="<?=app_url('superadmin/index.php')?>">Mitra / Client</a><a href="<?=app_url('superadmin/logout.php')?>">Keluar</a><p class="footer-note">DSG /v3 dan NMS tidak disentuh.</p></aside><main class="main"><div class="topline"><div><h1>Control Center Mitra</h1><p>Approve, disable, dan kelola account AppsBilling komersial.</p></div><a class="btn btn-light" target="_blank" href="<?=app_url('register.php')?>">Buka Form Registrasi</a></div><?php if($m=flash('ok')):?><div class="alert alert-ok"><?=e($m)?></div><?php endif;?><?php if($m=flash('err')):?><div class="alert alert-danger"><?=e($m)?></div><?php endif;?><div class="grid"><div class="card"><h3>Pending</h3><p><b><?= (int)$counts['pending']?></b> menunggu approval</p></div><div class="card"><h3>Active</h3><p><b><?= (int)$counts['active']?></b> tenant aktif</p></div><div class="card"><h3>Disabled</h3><p><b><?= (int)$counts['disabled']?></b> nonaktif sementara</p></div></div><div class="card" style="margin-top:18px"><h3>Daftar Mitra</h3><div class="table-wrap"><table class="table"><thead><tr><th>Mitra</th><th>No Akun</th><th>Kontak</th><th>Status</th><th>DB</th><th>Dibuat</th><th>Aksi</th></tr></thead><tbody><?php foreach($tenants as $t):?><tr><td><b><?=e($t['company_name'])?></b><br><small><?=e($t['tenant_uid'])?></small></td><td><span class="account-pill"><?=e($t['account_no'] ?: '-')?></span></td><td><?=e($t['owner_name'])?><br><small><?=e($t['phone'])?> <?=e($t['email'])?></small></td><td><span class="badge <?=e($t['status'])?>"><?=e($t['status'])?></span></td><td><small><?=e($t['db_path']?'ready':'not provisioned')?></small></td><td><?=e($t['created_at'])?></td><td><div class="actions"><form method="post"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="tenant_id" value="<?=$t['id']?>"><?php if($t['status']==='pending'):?><button class="btn btn-ok mini" name="action" value="approve">Approve</button><?php endif;?><?php if($t['status']==='active'):?><button class="btn btn-warn mini" name="action" value="disable">Disable</button><?php endif;?><?php if(in_array($t['status'],['disabled','deleted'],true)):?><button class="btn btn-ok mini" name="action" value="reactivate">Aktifkan</button><?php endif;?><button onclick="return confirm('Soft delete tenant ini? DB tidak dihapus otomatis.')" class="btn btn-danger mini" name="action" value="delete">Delete</button></form></div></td></tr><?php endforeach;?><?php if(!$tenants):?><tr><td colspan="7">Belum ada registrasi mitra.</td></tr><?php endif;?></tbody></table></div></div></main></div><?php render_footer(); ?>
